name: ai
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11  # 2.2.2 pytorch's torch.compile does not work with 3.12 yet
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - pandas
  - numpy
  - matplotlib
  - tqdm
  - requests
  - ipdb
  - pdbpp
  - jupyterlab
  - ipywidgets
  - nodejs
  - scipy
  - scikit-learn
  - pillow
  - pip
  - ripgrep
  - pip:
    - timm
    - transformers
    - diffusers
    - accelerate
    - einops
    - opencv-contrib-python
    - tiktoken
    - blobfile
    - datasets
    - wandb
    - jupyter_collaboration

