name: ai
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipython
  - ipdb
  - pdbpp
  - jupyterlab
  - ipywidgets
  - ipykernel
  - nodejs
  - pip
  - pip:

    - requests
    - tqdm

    - matplotlib
    - numpy
    - pandas
    - opencv-contrib-python
    - pillow

    - torch
    - torchvision
    - einops

    - tiktoken
    - transformers
    - datasets
    - wandb
    